### ISSUE TITLE
Update initramfs to be compatible with core0 0.12.0

### ISSUE THREAD

**Issue by zaibon** [g8os/initramfs#11]
Need to update the build compile the gorocksbd lib.

Two solutions:
- use the `-tags=embed`
- build rocksdb ourself and like against it.

**Comment by maxux** [comment]
On last branch https://github.com/g8os/initramfs/tree/0.12.0
- [x] rocksdb (as shared library)
- [x] unionfs-fuse integrated
- [ ] gorocksdb (need to confirm how to integrate it)
