### ISSUE TITLE
Add udev-binary plus rules to dynamically load kernel modules

### ISSUE THREAD

**Issue by muhamadazmy** [g8os/initramfs#13]
Also the kernel build might need to have more stuff as modules now, instead of built in. Then udev will be able to load the required modules for the hardware.

This also might means we don't need the modprobe config files anymore, the one that loads generic network cards modules.

**Comment by maxux** [comment]
`udev` (`eudev`) support added on https://github.com/g8os/initramfs/commit/beb65b377c4bbe04418e2450e8940885134c3e41

**Comment by maxux** [comment]
Confirmed after some test on real hardware.
The usage of a static `modprobe` list should still be used to force some modules (like `fuse`) which are not automatically probed.
